govsso-inproxy:
  admin:
    base-url: https://admin.localhost:17443/
    token-request-allowed-ip-addresses-storage-path: ipaddresses
    tls:
      trust-store: classpath:inproxy.localhost.admin.truststore.p12
      trust-store-password: changeit

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          include:
            - certificates
            - diskSpace
            - readinessState
            - refreshScope
  endpoints:
    web:
      exposure:
        include: configprops,env,health,info
  info:
    git:
      mode: full
    java:
      enabled: true
    os:
      enabled: true

server:
  error:
    whitelabel:
      enabled: false
  port: 13443
  forward-headers-strategy: NONE # Under main this cannot be enabled by default, because docker-compose.yml doesn't have another proxy in front of inproxy that would always set X-Forwarded-For header. X-Forwarded-For value that could be set outside of your own infrastructure, cannot be trusted.
  ssl:
    enabled: true
    enabled-protocols: TLSv1.3
    key-store: classpath:inproxy.localhost.keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    protocol: TLS

spring:
  application:
    name: govsso-inproxy
  main:
    banner-mode: off
  cloud:
    discovery:
      client:
        # Health indicators are always UP with simple discovery client, therefore unnecessary.
        health-indicator:
          enabled: false
        composite-indicator:
          enabled: false
    loadbalancer:
      health-check:
        interval: 5s
      cache:
        enabled: false
    gateway:
      default-filters:
        - RemoveRequestHeader=traceparent
        - RemoveRequestHeader=tracestate
        - RemoveRequestHeader=elastic-apm-traceparent
      forwarded:
        enabled: false
      x-forwarded:
        enabled: false
